export const plans = [
  {
    plan_id: "price_1R1nNaP3lkFdaee3v9vay7c6",
    plan_name: "Basic",
    duration: "Monthly",
    price: "$199",
    features: [
      "1 Admin User",
      "Basic Dashboard",
      "Task Tracking (up to 100 tasks)",
      "Project Management Tools",
      "Standard Reporting",
      "Role-Based Access Control",
      "Employee Management (up to 100 employees)",
      "Document Sharing (up to 1GB)",
      "Email Support",
      "Third-Party Integrations",
      "Time Tracking",
    ],
  },
  {
    plan_id: "price_1R1nPFP3lkFdaee3nuJPl8mS",
    plan_name: "Pro",
    duration: "Monthly",
    price: "$399",
    features: [
      "5 Admin Users",
      "Advanced Dashboard with KPIs",
      "Unlimited Tasks",
      "Customizable Workflows",
      "Project Management Tools",
      "Advanced Reporting and Analytics",
      "Role-Based Access Control",
      "Employee Management (up to 150 employees)",
      "Document Sharing (up to 10GB)",
      "Inventory Management",
      "CRM Integration",
      "Priority Email Support",
      "APIs for Custom Integrations",
      "Time and Expense Tracking",
    ],
  },
  {
    plan_id: "price_1R1nQ5P3lkFdaee3igrctc6N",
    plan_name: "Enterprise",
    duration: "Monthly",
    price: "$599",
    features: [
      "Unlimited Admin Users",
      "Full Dashboard with Real-Time Data",
      "Unlimited Tasks and Custom Workflows",
      "Complete Project Lifecycle Management",
      "Advanced Security and Compliance Features",
      "Unlimited Employee Management",
      "Unlimited Document Storage",
      "Full CRM Suite",
      "Multi-Currency and Multi-Language Support",
      "Vendor and Supplier Management",
      "AI-Powered Insights and Automation",
      "Custom Branding",
      "24/7 Priority Support",
      "Dedicated Account Manager",
      "Onboarding and Training",
      "24/7 Monitoring and Alerts",
      "Custom SLA Agreements",
    ],
  },
  // Yearly Plans
  {
    plan_id: "price_1R1nQxP3lkFdaee348NMdsvS",
    plan_name: "Basic",
    duration: "Yearly",
    price: "$1999",
    features: [
      "1 Admin User",
      "Basic Dashboard",
      "Task Tracking (up to 100 tasks)",
      "Project Management Tools",
      "Standard Reporting",
      "Role-Based Access Control",
      "Employee Management (up to 100 employees)",
      "Document Sharing (up to 5GB)",
      "Email Support",
      "Third-Party Integrations",
      "Time Tracking",
    ],
  },
  {
    plan_id: "price_1R1nRXP3lkFdaee3CtAROmwC",
    plan_name: "Pro",
    duration: "Yearly",
    price: "$3999",
    features: [
      "5 Admin Users",
      "Advanced Dashboard with KPIs",
      "Unlimited Tasks",
      "Customizable Workflows",
      "Project Management Tools",
      "Advanced Reporting and Analytics",
      "Role-Based Access Control",
      "Employee Management (up to 150 employees)",
      "Document Sharing (up to 50GB)",
      "Inventory Management",
      "CRM Integration",
      "Priority Email Support",
      "APIs for Custom Integrations",
      "Time and Expense Tracking",
    ],
  },
  {
    plan_id: "price_1R1nS7P3lkFdaee36Uov4BPY",
    plan_name: "Enterprise",
    duration: "Yearly",
    price: "$5999",
    features: [
      "Unlimited Admin Users",
      "Full Dashboard with Real-Time Data",
      "Unlimited Tasks and Custom Workflows",
      "Complete Project Lifecycle Management",
      "Advanced Security and Compliance Features",
      "Unlimited Employee Management",
      "Unlimited Document Storage",
      "Full CRM Suite",
      "Multi-Currency and Multi-Language Support",
      "Vendor and Supplier Management",
      "AI-Powered Insights and Automation",
      "Custom Branding",
      "24/7 Priority Support",
      "Dedicated Account Manager",
      "Onboarding and Training",
      "24/7 Monitoring and Alerts",
      "Custom SLA Agreements",
    ],
  },
];
